name: Deploy to AWS EC2

on:
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Deploy to ECS
      run: |
        ssh -o StrictHostKeyChecking=no -A $EC2_USER@$EC2_INSTANCE_IP "
          ssh $EC2_USER_BACKEND@$EC2_INSTANCE_BACKEND_IP -o StrictHostKeyChecking=no '
            cd cc-uts-backend
            sudo git pull origin master
            npm install
            npm run build
            pm2 delete nextjs
            pm2 start npm --name "nextjs" -- start
            pm2 save
            sudo systemctl restart nginx
          '
        "
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_INSTANCE_IP: ${{ secrets.EC2_INSTANCE_IP }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_INSTANCE_BACKEND_IP: ${{ secrets.EC2_INSTANCE_BACKEND_IP }}
        EC2_USER_BACKEND: ${{ secrets.EC2_USER_BACKEND }}
